services:
  mongo:
    # restart: always
    image: mongo:latest
#    command: [--auth]
    volumes:
      - /var/lib/mongo
    ports:
      - "27017:27017"
    networks:
      - dict_network

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    # restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - dict_network

#  memcached:
#    image: memcached:latest
#    container_name: memcached
#    command: "-I 15M"
#    ports:
#      - "11211:11211"
#    networks:
#      - agg_network

  server:
    container_name: dict_server
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: ./entrypoint.sh
    env_file:
      - ./config/secrets.env
    volumes:
      - ./server:/app/server
    networks:
      - dict_network
    ports:
      - "5005:5005"
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: frontend
  #     target: development
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend/src:/code/src
  #     - /code/node_modules
  #   networks:
  #     - dict_network
  #   # depends_on:
  #     # - backend

volumes:
  ollama:
    driver: local

networks:
  dict_network:
    name: dict_network
    driver: bridge