# API:
API_STATUS_SUCCESS = 'Success'
API_STATUS_PARTIAL = 'Partial'
API_STATUS_FAILURE = 'Failure'
API_STATUS_WARNING = 'Warning'
API_STATUS_ERROR = 'Error'

# Frontend
DEFAULT_PAGE = 1
DEFAULT_PER_PAGE = 100
DEFAULT_DESCRIPTION_LENGTH = 250  # number of characters.
